// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using starTEDSystem.Entities;

#nullable disable

namespace starTEDSystem.DAL
{
    public partial class StarTEDContext : DbContext
    {
        public StarTEDContext()
        {
        }

        public StarTEDContext(DbContextOptions<StarTEDContext> options)
            : base(options)
        {
        }

        public virtual DbSet<SchoolProgram> Programs { get; set; }
        public virtual DbSet<ProgramCourse> ProgramCourses { get; set; }
        public virtual DbSet<School> Schools { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<SchoolProgram>(entity =>
            {
                entity.Property(e => e.DiplomaName).IsUnicode(false);

                entity.Property(e => e.ProgramName).IsUnicode(false);

                entity.Property(e => e.SchoolCode).IsUnicode(false);

                entity.HasOne(d => d.SchoolCodeNavigation)
                    .WithMany(p => p.Programs)
                    .HasForeignKey(d => d.SchoolCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_dbo.Programs_dbo.Schools_SchoolCode");
            });

            modelBuilder.Entity<ProgramCourse>(entity =>
            {
                entity.Property(e => e.CourseId).IsUnicode(false);

                entity.HasOne(d => d.Program)
                    .WithMany(p => p.ProgramCourses)
                    .HasForeignKey(d => d.ProgramId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_dbo.ProgramCourses_dbo.Programs_ProgramID");
            });

            modelBuilder.Entity<School>(entity =>
            {
                entity.HasKey(e => e.SchoolCode)
                    .HasName("PK_dbo.Schools");

                entity.Property(e => e.SchoolCode).IsUnicode(false);

                entity.Property(e => e.SchoolName).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}