// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace starTEDSystem.Entities
{
    [Index(nameof(CourseId), Name = "IX_CourseID")]
    [Index(nameof(ProgramId), Name = "IX_ProgramID")]
    [Index(nameof(ProgramId), nameof(CourseId), Name = "UN_dbo.ProgramCourses_ProgramIDCourseID", IsUnique = true)]
    public partial class ProgramCourse
    {
        [Key]

        public int ProgramCourseId { get; set; }

        public int ProgramId { get; set; }
        [Required]
        [StringLength(7)]
        public string CourseId { get; set; }
        public bool Required { get; set; }
        [StringLength(50)]
        public string Comments { get; set; }
        public int SectionLimit { get; set; }
        public bool Active { get; set; }

        public virtual SchoolProgram Program { get; set; }
    }
}