// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace starTEDSystem.Entities
{
    [Index(nameof(SchoolCode), Name = "IX_SchoolCode")]
    public partial class SchoolProgram
    {
        public SchoolProgram()
        {
            ProgramCourses = new HashSet<ProgramCourse>();
        }

        [Key]
        public int ProgramId { get; set; }
        [Required]
        [StringLength(100)]
        public string ProgramName { get; set; }
        [StringLength(100)]
        public string DiplomaName { get; set; }
        [Required]
        [StringLength(10)]
        public string SchoolCode { get; set; }
        public decimal Tuition { get; set; }
        public decimal InternationalTuition { get; set; }


        public virtual School SchoolCodeNavigation { get; set; }

        public virtual ICollection<ProgramCourse> ProgramCourses { get; set; }
    }
}